version: "3.2"

secrets:
  nldas-password:
    file: ./secrets/nldas-password
  nldas-username:
    file: ./secrets/nldas-username
  
services:
  backend:
    build:
      context: ./backend
    depends_on:
      - redis
    environment:
      - NLDAS_USERNAME_FILE=/run/secrets/nldas-username
      - NLDAS_PASSWORD_FILE=/run/secrets/nldas-password
    restart: unless-stopped
    secrets:
      - nldas-password
      - nldas-username
    volumes:
      - ./cache:/home/flask/cache
  frontend:
    build:
      context: ./frontend
    depends_on:
      - backend
      - redis
    restart: unless-stopped
  nginx:
    depends_on:
      - frontend
    image: nginx:stable
    ports:
      - 8080:80
    restart: unless-stopped
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
  redis:
    image: redis:6-alpine
    restart: unless-stopped
    volumes:
      - ./.redis:/var/lib/redis
